#!/usr/bin/perl 
#v3.0

#delete_allele_conflicts.pl $kmer_counts 
# delete kmers from this genome in wihch the central base differs but the surrounding context is the same.

no warnings 'deprecated';

my $kmer_counts_file=$ARGV[0];

# Output is <source>.conflictsDeleted.
my $out=$kmer_counts_file.".conflictsDeleted";


my $seqLine=`head -1 $kmer_counts_file `;
my $seq;
my $k;
if ($seqLine=~ /(\w+)\s+\d+/) {
    $seq=$1;
    $k=length($seq);
}


my %kmers=();

# Create a hash of a hash of counts.  Assume all lines have same # chars as
# first line of the file (above).  Take out the center character and replace it
# with a '.'.  Within that hash entry, store the count for each value that was
# seen in that center position. - JN
open IN,"$ARGV[0]";
while (my $line=<IN>) {
    chomp $line;
   # print "line: $line\n";
    my ($seq,$freq)=split/\s+/,$line;
   # print "seq=$seq\n";
   # print "freq: $freq\n";
    my $s1=substr($seq,0,(($k-1)/2));
 
    my $s2=substr($seq,(($k-1)/2)+1);
    my $center=substr($seq,(($k-1)/2),1);
    my $j=$s1.".".$s2; # snp
    #print "$j\t$center\t$freq\n";
  
    $kmers{$j}{$center}=$freq;

}
close IN;


# This step will select only k-mers that don't have a corresponding k-mer in 
# the set that differs by the center monomer. - JN

open OUT,">$out";
my %keep=();
# Unnecessary sort step (this part doesn't depend on order, and a more relevant
# sort is done for the output, making this one irrelelvant). - TODO - JN
foreach my $seq (sort keys %kmers ) {
    
    @center= keys(%{$kmers{$seq}});
    if ( scalar @center  == 1) {
	my ($s1,$s2)=split/\./,$seq;
	my $kseq= $s1.$center[0].$s2;
	$keep{$kseq}=1;
	#print OUT $s1,$center[0],$s2,"\t$kmers{$seq}{$center[0]}\n";
    }
}

# Output all kmers found in the step above.
# Note that output is sorted by k-mer. - JN
foreach my $kseq (sort keys %keep) {
    print OUT "$kseq\n";
}

close OUT;
