#!/usr/bin/perl
#v3.0

# example: fasta_remove_new_lines.pl input_fasta 
# generates input_fasta_no_breaks
no warnings 'deprecated';

my $infile     = $ARGV[0];
open INDATA,"$infile" or die "Can't open $infile: $!\n";

my %track_repeats=();
my $sequence = "";
my $id;

while (my $line = <INDATA>) {
    
    if ($line =~ /^>(.*)/) {
	if ($sequence ne "") {
	    
	    if (!defined $track_repeats{$id} ) {
		print  ">$id\n",uc($sequence),"\n";
		$track_repeats{$id}++;
	    } else {
		print STDERR "More than one sequence has the identifier $id. Adding a count to name.\n";
		$track_repeats{$id}++;
		$id .= "_".$track_repeats{$id};
		print  ">$id\n",uc($sequence),"\n";
	    }
	}
	$id = $1;
	chomp($id);
	
	$id =~ s/\r//g; # delete carriage returns
	$id =~ s/\t/ /g; # substitute tabs with spaces
	$id =~ s/\s+/ /g;
	
	if ($id =~ /^(\S+)\s+(.*)/) {
	    $name=$1;
	    $name_part2=$2;
	    
	    $name =~ s/\|/_/g;
	    $name =~ s/,//g;
	    $name =~ s/\+/plus/g;
	    $name =~ s/\[//g;
	    $name =~ s/\]//g;
	    $name =~ s/\(//g;
	    $name =~ s/\)//g;
	    $name =~ s/\//-/g;
	    $name =~ s/[\t\r\s]+/_/g;
	    $name =~ s/_+/_/g;
	    $name =~ s/\://g;
	    
	    $name2 =substr($name,0,88);
	    
	    $id =$name2." ".$name_part2;
	}
	
	$sequence = "";
    } else {
	chomp($line);
	my $length_seq=length($line);
	# $line =~ s/[-|\*]//g; #Get rid of "-" and "*" if it's from an alignment
	$line =~ s/[\n\t\r]//g; # Get rid of spaces, tabs, and new lines
	if ($length_seq < 1e8) {
	    $line =~ s/[^atcgATCG]/N/g; # replace non-ATCG chars with N
            #  it fails with long sequences like 2GB, but non-ATCGN crash HreFinder so i like to remove if possible
	    $line =~ s/\s//g;
	}	
	$sequence .= $line;
    }
    
}
    
# Add last one
if (defined $id) {
    
    if (!defined  $track_repeats{$id} ) {
	print  ">$id\n",uc($sequence),"\n";
	$track_repeats{$id}++;
    } else {
	print STDERR "More than one sequence has the identifier $id. Adding a count to name.\n";
	$track_repeats{$id}++;
	$id .= "_".$track_repeats{$id};
	print  ">$id\n",uc($sequence),"\n";
    }
    
    $num_genomes++;
}

close INDATA or warn  "Can't close $infile: $!\n";

 
