#!/usr/bin/env python3

"""
Description: 
AccNum.txt is a file of accession numbers

Usage: 
GenbankDownload pathToThegenomeFasta file
"""
#********************* MODULES**********************
from __future__ import division
from __future__ import print_function
import sys
import os
import os.path
import sys
import re #regular expressions
import time
from Bio import Entrez
#******************* FUNCTION DEFINITIONS *******************



#********************** Main *************************
#variables
fileExist = ''
pathToFastaGenome = sys.argv[1]
accnum = ''
GenomeFile = ''



#does the file genbank_from_NCBI.gb esist?
fileExist = os.path.isfile('./genbank_from_NCBI.gbk') #'genbank_from_NCBI.gbk'
#print(fileExist)
if fileExist == True: # if the file does  exist do nothing
	pass
elif fileExist == False: #if the file does not exist create it
	OUTFILE = open('genbank_from_NCBI.gbk', 'w')
	#OUTFILE.write('\n')
	OUTFILE.close()
	
#print(pathToFastaGenome)

#extract the accession number from the sequence file header
INFILE = open(pathToFastaGenome, 'rU')
line = INFILE.readline()
temp = line.split()
accnum = temp[0]
accnum = accnum.lstrip('>')
print(accnum)

#find the NCBI ID for the accnum
Entrez.email = 'barryghall@gmail.com'
handle = Entrez.esearch(db="nuccore", term=accnum, retmax=100)
records = Entrez.read(handle) ##records is a dict
#print(records, '\n\n')
identifiers = records['IdList']

time.sleep(1)
#for IdList in records.keys():

ID = records['IdList']
ID = str(ID)
ID.replace('\'','>')


# download the accnum file
handle = Entrez.efetch(db="nuccore", id=accnum, retmax="100", rettype="gb", retmode="text") #, retmode="text"
         

text = handle.read()#Entrez.read(handle)


OUTFILE = open('genbank_from_NCBI.gbk','a')

for line in text:
	OUTFILE.write(line)


OUTFILE.close()
time.sleep(1)
