#!/usr/bin/perl
#v3.0

no warnings 'deprecated';

use Statistics::Descriptive;

my $in=$ARGV[0]; # list of counts
my $percentile=$ARGV[1]; # get count with this % of data 

open IN,"$in";
my @data = <IN>;
close IN;
chomp @data;
  
my $stat = Statistics::Descriptive::Full->new();
$stat->add_data(@data);

my $median=$stat->median;
my $mean= $stat->mean;
print STDERR  "median $median\n";
print  STDERR "mean $mean\n";
my $halfway=int(($median+$mean)/2);
#print "halfway bewteen median and mean: $halfway\n";
print "$halfway\n";
#print "q1 ", $stat->quantile(1),"\n";
#print "q2 ",$stat->quantile(2),"\n";
#print "q3 ",$stat->quantile(3),"\n";
#print "q4 ",$stat->quantile(4),"\n";

#print "mode ", $stat->mode,"\n";

#foreach $p qw(50 60 70 80 90 95) {
#    my $x=$stat->percentile($p);
#    print "smallest value is $x for which freq>=$p";
    
#}
