#!/usr/bin/env python

"""
Description: 
AccNum.txt is a file of accession numbers

Usage: 
GenbankDownload pathToThegenomeFasta file
"""
#********************* MODULES**********************
from __future__ import division
from __future__ import print_function
import sys
import os
import os.path
import sys
import re #regular expressions
import time

# Use the correct module based on the python version.
if sys.version_info[0] == 2:
	import httplib as httplib

else: # More modern python
	import http.client as httplib

# XML parsing used below is common to 2.7 and 3.x
import xml.etree.ElementTree as ET

# Entrez Utils global variable (hostname for NIH EUtils)
eutilsHost = "eutils.ncbi.nlm.nih.gov"


#******************* FUNCTION DEFINITIONS *******************
def get(hostname, uri):
	GET="GET"

	connection = httplib.HTTPSConnection(hostname)

	connection.request(GET, uri)
	response = connection.getresponse()

	data = response.read()

	connection.close()

	return (response.status, response.reason, data)


def EFetch(acc, retmode="text", rettype="fasta", db="nuccore", email="ksnp-dev@kissake.net"):

	efetchPrefix = "/entrez/eutils/efetch.fcgi?"
	argSeparator = "&"

	arguments={
		"tool": "kSNP4",
		"email": email,
		"db": db,
		"rettype": rettype,
		"retmode": retmode,
		"id": acc,
	}

	URI = efetchPrefix + argSeparator.join([ "=".join(item) for item in arguments.items() ])
	time.sleep(0.34) # Sleep for 1/3 of a second here to enforce a rate limit of 3 requests per second.

	(status, reason, fetched) = get(eutilsHost,URI)

	if status != 200:
		sys.stderr.write("HTTP Error %d: %s\n" % (status, reason))
		sys.exit(1)

	return fetched

def ESearch(searchTerm, db="nuccore", email="ksnp-dev@kissake.net", retmax=100):

	idListParent='IdList'
	idListChildren='Id'

	efetchPrefix = "/entrez/eutils/esearch.fcgi?"
	argSeparator = "&"

	arguments={
		"tool": "kSNP4",
		"email": email,
		"db": db,
		"rettype": 'uilist',
		"retmode": 'xml',
		"term": searchTerm,
		"idtype": "acc",
		"retmax": str(retmax),
	}

	URI = efetchPrefix + argSeparator.join([ "=".join(item) for item in arguments.items() ])
	time.sleep(0.34) # Sleep for 1/3 of a second here to enforce a rate limit of 3 requests per second.

	(status, reason, searchData) = get(eutilsHost,URI)

	if status != 200:
		sys.stderr.write("HTTP Error %d: %s\n" % (status, reason))
		sys.exit(1)
	
	searchRoot = ET.fromstring(searchData)
	ids = [ element.text for element in searchRoot.find(idListParent).findall(idListChildren) ]

	return ids


#******************* FUNCTION DEFINITIONS *******************
def extractAccNum(line):
	temp = line.split()
	accnum = temp[0]
	accnum = accnum.lstrip('>')	
	AccNumList.append(accnum)
	print(accnum)
	return(accnum)

#********************** Main *************************
#variables
fileExist = ''
pathToFastaGenome = sys.argv[1]
accnum = ''
GenomeFile = ''
seqData = False  # et to True iuf line is sequence data
AccNumList = []

startTime = time.time()

#does the file genbank_from_NCBI.gb esist?
fileExist = os.path.isfile('./genbank_from_NCBI.gbk') #'genbank_from_NCBI.gbk'
#print(fileExist)
if fileExist == True: # if the file does  exist do nothing
	pass
elif fileExist == False: #if the file does not exist create it
	OUTFILE = open('genbank_from_NCBI.gbk', 'w')
	#OUTFILE.write('\n')
	OUTFILE.close()
	
#print(pathToFastaGenome)

#extract the accession number from the sequence file header
INFILE = open(pathToFastaGenome, 'r')

for line in INFILE:
	if line.startswith('>'):
		accnum = extractAccNum(line)
INFILE.close


# download the accnum file
#handle = Entrez.efetch(db="nuccore", id=accnum, retmax="100", rettype="gb", retmode="text") #, retmode="text"
#text = handle.read() #Entrez.read(handle)

#temp = text.split('\n')

OUTFILE = open('genbank_from_NCBI.gbk', 'a',)

for i in range(len(AccNumList)): #for each accession number
	accnum = AccNumList[i]
	#find the NCBI ID for the accnum
	EntrezEmail = 'barryghall@gmail.com'
	IDs = ESearch(accnum, db='nuccore', email=EntrezEmail, retmax=100)
	if len(IDs) > 0:
		ID = str(IDs[0])
		#print("The ID is ", ID)
		try:
			text = EFetch(db="nuccore", acc=accnum, retmax="100", rettype="gb", retmode="text") #, retmode="text"
		except:
			continue
		temp = text.split('\n')	
		for j in range(len(temp)):	
			if temp[j].startswith("ORIGIN"):
				OUTFILE.write('{0}\n'.format(temp[j]))
				OUTFILE.write('//\n\n')		
				break
			else:
				 # download the accnum file
				 OUTFILE.write('{0}\n'.format(temp[j]))

		OUTFILE.write('//\n\n')
	time.sleep(1)

OUTFILE.close()
endTime = time.time()
elapsedTime = endTime-startTime
print("Used ",elapsedTime, "seconds.")

