#!/usr/bin/perl
#v3.0


#parse_protein_annotation_counts.pl SNP_annotations >  Protein_Annotation_counts

no warnings 'deprecated';

my %prot=();
open IN,"$ARGV[0]";
while (my $line=<IN>) {
    chomp $line;
    if ($line !~ /SNPPositiononProtein/) {

	my @x=split/\t/,$line;
	$locus=shift @x;
	$context=shift @x;
	$ns=shift @x;
	$annotation_type=shift @x;
	# print "locus $locus\ncontext $context\nns $ns\n";
	$aa=shift @x;
	$codon=shift @x;
	$pos_prot=shift @x;
	$id=shift @x;
	$fasta_header=shift @x;
	$posInRefGenome=shift @x;
	$genomeGI=shift @x;
	@annotation_array=@x;
	$annotation=join " ",@x;



	if ($annotation !~ /\S+/) {
	    $annotation="NonCoding\t";
	    @annotation_array=();
	}
        #print "annotation: $annotation\n";
	$prot{$annotation}{$ns}++;
	@{$annotation_hash{$annotation}}=@annotation_array;
    }
    
}

print "#SNPs\tNumNonSynon\tNumSynon\tNS/Sratio\tAnnotation\n";
foreach my $protein (sort keys %prot) {
    my $NS_Sratio;
    if ($prot{$protein}{0}>0) {
	$NS_Sratio=sprintf("%.2f",$prot{$protein}{1}/$prot{$protein}{0});
    } else {
	$NS_Sratio="inf";
	$prot{$protein}{0}=0;
    }
    if (!defined $prot{$protein}{1}) { $prot{$protein}{1}=0;}

    my $total=$prot{$protein}{1}+$prot{$protein}{0};
    print "$total\t$prot{$protein}{1}\t$prot{$protein}{0}\t$NS_Sratio";
    foreach my $entry (@{$annotation_hash{$protein}}) {
	print "\t$entry";
    }
    print "\n";
}

