#!/bin/bash

# Usage: select_node_annotations <node> <tree method>
# 
# Creates node.<node>.<tree method>.annotations containing the SNP_annotations for just the indicated node.
# 
# <node> is the number of the node you want or the strain name for leaf nodes, ascertained from the 
# tree_AlleleCounts.(SNPs_all|core_SNPs|SNPs_in_majority0.x).(ML|NJ|parsimony).NodeLabel.tre file or the 
# corresponding Node_SNP_counts file.  The <tree method> is the set of SNPs to build a tree from and the
# tree construction method separated by a period. (see examples)
# 
# Example1:  select_node_annotations 59 SNPs_all.ML
# Example2:  select_node_annotations EcoW SNPs_in_majority0.75.parsimony



ANNOTATIONS="SNPs_all_annotated"

NODE="${1}"
TREE="${2}"

# Input file:
TREEFILE="ClusterInfo.${TREE}"

# Output files:
NODELOCI="node.${NODE}.${TREE}.loci"
NODEANNOTATIONS="node.${NODE}.${TREE}.annotations"

# If the input file doesn't exist, or if no node identifier was specified,
# remind the user how to use the script.
if [ ! -f "${TREEFILE}" -o -z "${NODE}" ]
then
    cat <<EOF
Usage: select_node_annotations <node> <tree method>

Creates node.<node>.<tree method>.annotations containing the SNP_annotations for just the indicated node.

<node> is the number of the node you want or the strain name for leaf nodes, ascertained from the 
tree_AlleleCounts.(SNPs_all|core_SNPs|SNPs_in_majority0.x).(ML|NJ|parsimony).NodeLabel.tre file or the 
corresponding Node_SNP_counts file.  The <tree method> is the set of SNPs to build a tree from and the
tree construction method separated by a period. (see examples)

Example1:  select_node_annotations 59 SNPs_all.ML
Example2:  select_node_annotations EcoW SNPs_in_majority0.75.parsimony

EOF

    if [ ! -f "${TREEFILE}" ]
    then
        echo "File ${TREEFILE} not found."
    else
        echo "Node not specified. (${NODE})"
    fi
    exit 1
fi


grep -w Node.${NODE} "${TREEFILE}" | awk '{print  "^" $1}' | sort > "${NODELOCI}"

if [ -s "${NODELOCI}" ] 
then
    grep -w -f "${NODELOCI}" "${ANNOTATIONS}">> "${NODEANNOTATIONS}"
else
    rm "${NODELOCI}"
    echo "Node (Node.${NODE}) not found.  Look in ${TREEFILE} for candidates."
    exit 1
fi 
