#!/usr/bin/perl
#v3.0

# subset_mer_list.pl >! mer_list
no warnings 'deprecated';

my @bases = qw(A C G T);

# Note that @zarray and $count are unneeded in this script. TODO - JN
    my $count=0;
    foreach $w (@bases) {
	foreach $x (@bases) {
	    foreach $y (@bases) {
		foreach $m (@bases) {
		    #foreach $t (@bases) {
		    #foreach $s (@bases) {
		    my $z=$w.$x.$y.$m;
		    $zarray[$count]=$z;
		    print "$z.mers\n";
		    $count++;
		    #}
		    #}
		}
	    }
	}
    }



